<?php


?>
<option value="52" selected="selected">México</option>	
<option value="1">Estados Unidos</option>
<option value="44">Inglaterra</option>
<option value="1">Canadá</option>
<option value="61">Australia</option>
<option value="91">India</option>
<option value="0">-----------------</option>
<option value="93">Afganistán</option>
<option value="355">Albania</option>
<option value="49">Alemania</option>
<option value="376">Andorra</option>
<option value="244">Angola</option>
<option value="1 264">Anguila</option>
<option value="672 1">Antártida</option>
<option value="1 268">Antigua y Barbuda</option>
<option value="599">Antillas Holandesas</option>					
<option value="966">Arabia Saudita</option>
<option value="213">Argelia</option>
<option value="54">Argentina</option>
<option value="374">Armenia</option>
<option value="297">Aruba</option>
<option value="43">Austria</option>
<option value="994">Azerbaiyán</option>																								
<option value="1 242">Bahamas</option>
<option value="973">Bahrein</option>
<option value="880">Bangladesh</option>												
<option value="1 246">Barbados</option>
<option value="32">Bélgica</option>
<option value="501">Belice</option>
<option value="229">Benin</option>
<option value="1 441">Bermudas</option>
<option value="375">Bielorrusia</option>
<option value="95">Birmania</option>
<option value="591">Bolivia</option>
<option value="599 7">Bonaire</option>
<option value="387">Bosnia Y Herzegovina</option>
<option value="387">Botsuana</option>
<option value="55">Brasil</option>
<option value="673">Brunei</option>
<option value="359">Bulgaria</option>
<option value="226">Burkina Faso</option>
<option value="257">Burundi</option>
<option value="975">Bután</option>
<option value="238">Cabo Verde</option>
<option value="855">Camboya</option>
<option value="237">Camerún</option>
<option value="1">Canadá</option>
<option value="34">Cataluña</option>
<option value="235">Chad</option>
<option value="56">Chile</option>
<option value="86">China</option>
<option value="357">Chipre</option>
<option value="90 392">Chipre (Turquía)</option>
<option value="379">Ciudad del Vaticano</option>
<option value="57">Colombia</option>
<option value="269">Comores</option>
<option value="850">Corea del Norte</option>
<option value="82">Corea del Sur</option>
<option value="225">Costa de Marfil</option>
<option value="506">Costa Rica</option>						
<option value="385">Croacia</option>
<option value="53">Cuba</option>
<option value="599 9">Curaçao</option>
<option value="246">Diego García</option>
<option value="45">Dinamarca</option>
<option value="1 767">Dominica</option>
<option value="593">Ecuador</option>
<option value="20">Egipto</option>
<option value="503">El Salvador</option>
<option value="971">Emiratos Árabes Unidos</option>
<option value="291">Eritrea</option>
<option value="44">Escocia</option>
<option value="421">Eslovaquia</option>
<option value="386">Eslovenia</option>
<option value="34">España</option>
<option value="1">Estados Unidos</option>
<option value="372">Estonia</option>
<option value="251">Etiopía</option>
<option value="63">Filipinas</option>
<option value="358">Finlandia</option>
<option value="679">Fiyi</option>
<option value="33">Francia</option>						
<option value="241">Gabon</option>
<option value="220">Gambia</option>
<option value="995">Georgia</option>
<option value="233">Ghana</option>
<option value="350">Gibraltar</option>
<option value="1 473">Granada</option>
<option value="30">Grecia</option>						
<option value="299">Groenlandia</option>
<option value="590">Guadalupe</option>
<option value="1 671">Guam</option>
<option value="502">Guatemala</option>
<option value="594">Guyana Francesa</option>
<option value="44 1481">Guernesey</option>
<option value="224">Guinea</option>
<option value="224">Guinea Ecuatorial</option>
<option value="245">Guinea Bissau</option>						
<option value="592">Guyana</option>						
<option value="509">Haití</option>
<option value="1 808">Hawái</option>
<option value="504">Honduras</option>
<option value="852">Hong Kong</option>
<option value="36">Hungría</option>
<option value="91">India</option>
<option value="62">Indonesia</option>
<option value="44">Inglaterra</option>
<option value="98">Irán</option>
<option value="964">Iraq</option>
<option value="44">Irlanda del Norte</option>												
<option value="247">Isla Ascensión</option>
<option value="47">Isla Bouvet</option>
<option value="44 1624">Isla de Man</option>
<option value="56 32">Isla de Pascua</option>
<option value="44">Isla del Sur de Georgia</option>
<option value="61">Isla Heard</option>
<option value="672 1">Isla Macquarie</option>
<option value="354">Islandia</option>						
<option value="358 18">Islas Åland</option>
<option value="1 345">Islas Caimán</option>						
<option value="34">Islas Canarias</option>						
<option value="61 89164">Islas Christmas</option>																		
<option value="61 89162">Islas Cocos</option>
<option value="682">Islas Cook</option>
<option value="44">Islas del Canal</option>
<option value="298">Islas Feroe</option>						
<option value="500">Islas Malvinas</option>
<option value="1 670">Islas Marianas</option>
<option value="692">Islas Marshall</option>
<option value="697">Islas Midway</option>
<option value="672 3">Islas Norfolk</option>
<option value="649">Islas Pitcairn</option>
<option value="677">Islas Salomón</option>
<option value="44">Islas Sandwich del Sur</option>
<option value="1 649">Islas Turcas y Caicos</option>
<option value="1 340">Islas Vírgenes</option>
<option value="1 284">Islas Vírgenes Británicas</option>												
<option value="972">Israel</option>
<option value="39">Italia</option>
<option value="1 876">Jamaica</option>
<option value="47">Jan Mayen Isla</option>
<option value="81">Japón</option>
<option value="44 1534">Jersey</option>
<option value="962">Jordania</option>
<option value="7">Kazajistán</option>
<option value="254">Kenia</option>
<option value="996">Kirguistán</option>
<option value="686">Kiribati</option>
<option value="381">Kosovo</option>
<option value="965">Kuwait</option>
<option value="856">Laos</option>
<option value="266">Lesoto</option>
<option value="371">Letonia</option>
<option value="961">Líbano</option>
<option value="231">Liberia</option>
<option value="218">Libia</option>
<option value="423">Liechtenstein</option>
<option value="370">Lituania</option>
<option value="352">Luxemburgo</option>						
<option value="853">Macao</option>
<option value="389">Macedonia</option>
<option value="261">Madagascar</option>
<option value="60">Malasia</option>
<option value="265">Malawi</option>
<option value="960">Maldivas</option>
<option value="223">Malí</option>
<option value="356">Malta</option>						
<option value="212">Marruecos</option>
<option value="596">Martinica</option>
<option value="230">Mauricio</option>
<option value="222">Mauritania</option>
<option value="262">Mayotte</option>
<option value="61">McDonald Islas</option>
<option value="52">México</option>
<option value="691">Micronesia</option>
<option value="373">Moldavia</option>						
<option value="377">Mónaco</option>						
<option value="976">Mongolia</option>
<option value="382">Montenegro</option>
<option value="1 664">Montserrat</option>
<option value="258">Mozambique</option>
<option value="264">Namibia</option>
<option value="674">Nauru</option>
<option value="977">Nepal</option>						
<option value="505">Nicaragua</option>
<option value="227">Níger</option>
<option value="234">Nigeria</option>
<option value="683">Niue</option>
<option value="47">Noruega</option>
<option value="687">Nueva Caledonia</option>
<option value="687">Nueva Zelanda</option>
<option value="968">Omán</option>
<option value="44">País de Gales</option>
<option value="31">Países Bajos</option>
<option value="92">Pakistán</option>
<option value="680">Palaos</option>
<option value="970">Palestina (ANP)</option>
<option value="507">Panamá</option>
<option value="675">Papúa Nueva Guinea</option>
<option value="675">Paraguay</option>
<option value="51">Perú</option>
<option value="689">Polinesia Francesa</option>
<option value="48">Polonia</option>
<option value="351">Portugal</option>						
<option value="1 787">Puerto Rico</option>
<option value="974">Qatar</option>
<option value="44">Reino Unido</option>
<option value="236">República Centroafricana</option>
<option value="420">República Checa</option>
<option value="374 47">República de Nagorno-Karabaj</option>
<option value="242">República del Congo</option>
<option value="243">República Democrática del Congo</option>
<option value="1 809">República Dominicana</option>												
<option value="262">Reunión y Mayotte</option>						
<option value="250">Ruanda</option>
<option value="40">Rumanía</option>
<option value="7">Rusia</option>
<option value="599 4">Saba</option>
<option value="212 28">Sáhara Occidental</option>
<option value="599 3">Saint-Eustaquio</option>
<option value="685">Samoa</option>
<option value="1 684">Samoa Americana</option>
<option value="1 869">San Cristóbal y Nieves</option>
<option value="378">San Marino</option>
<option value="508">San Pedro y Miquelón</option>
<option value="1 784">San Vicente y las Granadinas</option>						
<option value="290">Santa Helena</option>
<option value="1 758">Santa Lucía</option>
<option value="239">Santo Tomé y Príncipe</option>
<option value="221">Senegal</option>
<option value="381">Serbia</option>
<option value="248">Seychelles</option>
<option value="232">Sierra Leona</option>
<option value="65">Singapur</option>
<option value="1 721">Sint Maarten</option>
<option value="963">Siria</option>
<option value="252">Somalía</option>
<option value="94">Sri Lanka</option>
<option value="268">Suazilandia</option>						
<option value="27">Sudáfrica</option>
<option value="249">Sudán</option>
<option value="46">Suecia</option>
<option value="41">Suiza</option>
<option value="597">Surinam</option>
<option value="47">Svalbard</option>
<option value="66">Tailandia</option>
<option value="886">Taiwan</option>
<option value="255">Tanzania</option>
<option value="992">Tayikistán</option>
<option value="670">Timor Oriental</option>
<option value="228">Togo</option>
<option value="690">Tokelau</option>
<option value="676">Tonga</option>						
<option value="1 868">Trinidad y Tobago</option>
<option value="290 8">Tristán da Cunha</option>
<option value="216">Túnez</option>
<option value="993">Turkmenistán</option>
<option value="90">Turquía</option>
<option value="688">Tuvalu</option>
<option value="380">Ucrania</option>
<option value="256">Uganda</option>
<option value="598">Uruguay</option>
<option value="998">Uzbekistán</option>
<option value="678">Vanuatu</option>						
<option value="58">Venezuela</option>
<option value="84">Vietnam</option>
<option value="681">Wallis y Futuna</option>
<option value="967">Yemen</option>
<option value="253">Yibuti</option>						
<option value="260">Zambia</option>
<option value="255 24">Zanzibar</option>
<option value="263">Zimbabue</option>